### ISSUE TITLE
$_SERVER['REMOTE_USER']

### ISSUE THREAD

**Issue by andreli** [matomo-org/plugin-LoginHttpAuth#13]
The function getHttpAuthLogin() checks for $_SERVER['PHP_AUTH_USER'], $_ENV['AUTH_USER'], $_ENV['REMOTE_USER'] and $_ENV['REDIRECT_REMOTE_USER'].

I somehow ended up with an apache setup the has the REMOTE_USER in $_SERVER. Might be worth adding this to the list.

**Comment by mattab** [comment]
Hi @andreli Pull request will be welcome, ideally with the apache version + config that was used to reproduce the `$_SERVER['REMOTE_USER']`
